language: node_js
sudo: false
addons:
  firefox: "44.0.1"
cache:
  directories:
  - $HOME/.npm
  - $HOME/.nvm
  - $HOME/.cache/bower
  - app/bower_components
  - node_modules
node_js:
  - '6.2'
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm i -g bower@1.7.9 gulp@3.9.1
  - bower i
script:
  - npm test
env:
  global:
    - "CXX='g++-4.8'"
